### ISSUE TITLE
Defect: Login button does not work

### ISSUE THREAD

**Issue by MayuriSR** [swetabichpuriya/Sweta-Test#22]
![Log in Error.png](https://images.zenhubusercontent.com/5acafae94b5806bc2bce35a9/c3e80adb-29ed-4874-ae58-d1743ba98c58)

Steps to Reproduce:
1. Go to site ABC.
2. Enter valid User Name (ABC).
3. Enter valid password for user (XYZ). 
4. Click on Login Button.

Actual Result:
No action is performed on clicking Login button.User is not logged in.

Expected Result:
User should be logged in to Home page.

Environment: Chrome browser (Version 65)
Build Version: 1

Associated with user story #6

**Comment by swetabichpuriya** [comment]
Closing it to check if it is getting updated in testlink.
